### ISSUE TITLE
EXTERNAL-IP stuck on pending status

### ISSUE THREAD

**Issue by nanthan** [paulbouwer/hello-kubernetes#1]
When I run `kubectl get services` 

```
NAME               TYPE           CLUSTER-IP      EXTERNAL-IP   PORT(S)        AGE
hello-kubernetes   LoadBalancer   10.100.179.79   <pending>     80:30607/TCP   37m
```

and not have any errors in events service

---------------
edit : 
I change the type of service from LoadBalancer to NodePort because I run cluster on-prem. not support type LoadBalancer

**Comment by paulbouwer** [comment]
@nanthan - the instructions do lean towards cloud deployments (LoadBalancer). I'll add an issue for additional instructions for on-prem and local clusters.

Thanks for reporting and using.
