### ISSUE TITLE
Please provide a single file yaml, it's very useful

### ISSUE THREAD

**Issue by STRRL** [paulbouwer/hello-kubernetes#29]
Hi! I really love this project, I always use this project as an example when I show how Kubernetes could do to my friends. With a simple `kubectl apply -f <link>` I could raise some instances of an application, that's awesome.

But after using helm, there are more steps to do and more concepts to introduce, so I think providing a single file manifest might be better.

I think `helm template` could render that single file manifest without modifying anything already existing.

**Comment by dcorbe** [comment]
You can generate your own manifests by running `helm template .` in the helm chart's directory.

**Comment by STRRL** [comment]
I would generate one then upload it to the GitHub dist.
