### ISSUE TITLE
Build error from org.opencontainers.image.description

### ISSUE THREAD

**Issue by alljames** [paulbouwer/hello-kubernetes#4]
Failed to build this image using Kaniko. It's unhappy parsing the `'` character in the word `it's`.

```error building image: error building stage: failed to process "Provides a demo image to deploy to a Kubernetes cluster. It displays a message, the name of the pod and details of the node it's deployed to.": unexpected end of statement while looking for matching single-quote```

Will raise a quick PR to escape this character and link it to this issue :+1:

**Comment by paulbouwer** [comment]
Thanks @alljames - I simplified the message and fixed with some other items in PR #9. A new image is available at `paulbouwer/hello-kubernetes:1.6`.

**Comment by alljames** [comment]
Great, thank you!
